# Compose yml - Docker Documentation
# http://docs.docker.com/compose/yml/

db:
  build: db
  expose:
    - 5432
  env_file:
    - './conf/db.env'

webapp:
  build: webapp
  expose:
    - 5000
  restart: always
  links:
    - db
  command: bash -c 'sleep 10 && ./manage.py createdb && ./manage.py runserver -d -h 0.0.0.0 -p 5000'

nginx:
  build: nginx
  restart: always
  ports:
    - 80:80
  links:
    - webapp
  command: bash -c 'sleep 5 && nginx -g daemon off;'